/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AiIndexRouteImport } from './routes/ai.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as DashboardWishlistRouteImport } from './routes/dashboard.wishlist'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard.transactions'
import { Route as DashboardPurchasesRouteImport } from './routes/dashboard.purchases'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardDownloadsRouteImport } from './routes/dashboard.downloads'
import { Route as DashboardChangePasswordRouteImport } from './routes/dashboard.change-password'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as AiVivaGeneratorRouteImport } from './routes/ai.viva-generator'
import { Route as AiSmartSearchRouteImport } from './routes/ai.smart-search'
import { Route as AiResumeBuilderRouteImport } from './routes/ai.resume-builder'
import { Route as AiResearchAssistantRouteImport } from './routes/ai.research-assistant'
import { Route as AiProjectExplainerRouteImport } from './routes/ai.project-explainer'
import { Route as AiProjectAdvisorRouteImport } from './routes/ai.project-advisor'
import { Route as AiPptGeneratorRouteImport } from './routes/ai.ppt-generator'
import { Route as AiDocumentAnalyzerRouteImport } from './routes/ai.document-analyzer'
import { Route as AiCareerAdvisorRouteImport } from './routes/ai.career-advisor'
import { Route as AiAssistantRouteImport } from './routes/ai.assistant'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRevenueRouteImport } from './routes/admin.revenue'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminDownloadsRouteImport } from './routes/admin.downloads'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminProjectsNewRouteImport } from './routes/admin.projects.new'
import { Route as AdminCategoriesNewRouteImport } from './routes/admin.categories.new'
import { Route as AdminProjectsIdEditRouteImport } from './routes/admin.projects.$id.edit'
import { Route as AdminProjectsIdBuyersRouteImport } from './routes/admin.projects.$id.buyers'
import { Route as AdminCategoriesIdEditRouteImport } from './routes/admin.categories.$id.edit'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AiIndexRoute = AiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AiRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWishlistRoute = DashboardWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPurchasesRoute = DashboardPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDownloadsRoute = DashboardDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChangePasswordRoute = DashboardChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => DashboardRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoriesRoute,
} as any)
const AiVivaGeneratorRoute = AiVivaGeneratorRouteImport.update({
  id: '/viva-generator',
  path: '/viva-generator',
  getParentRoute: () => AiRoute,
} as any)
const AiSmartSearchRoute = AiSmartSearchRouteImport.update({
  id: '/smart-search',
  path: '/smart-search',
  getParentRoute: () => AiRoute,
} as any)
const AiResumeBuilderRoute = AiResumeBuilderRouteImport.update({
  id: '/resume-builder',
  path: '/resume-builder',
  getParentRoute: () => AiRoute,
} as any)
const AiResearchAssistantRoute = AiResearchAssistantRouteImport.update({
  id: '/research-assistant',
  path: '/research-assistant',
  getParentRoute: () => AiRoute,
} as any)
const AiProjectExplainerRoute = AiProjectExplainerRouteImport.update({
  id: '/project-explainer',
  path: '/project-explainer',
  getParentRoute: () => AiRoute,
} as any)
const AiProjectAdvisorRoute = AiProjectAdvisorRouteImport.update({
  id: '/project-advisor',
  path: '/project-advisor',
  getParentRoute: () => AiRoute,
} as any)
const AiPptGeneratorRoute = AiPptGeneratorRouteImport.update({
  id: '/ppt-generator',
  path: '/ppt-generator',
  getParentRoute: () => AiRoute,
} as any)
const AiDocumentAnalyzerRoute = AiDocumentAnalyzerRouteImport.update({
  id: '/document-analyzer',
  path: '/document-analyzer',
  getParentRoute: () => AiRoute,
} as any)
const AiCareerAdvisorRoute = AiCareerAdvisorRouteImport.update({
  id: '/career-advisor',
  path: '/career-advisor',
  getParentRoute: () => AiRoute,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AiRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDownloadsRoute = AdminDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProjectsRoute,
} as any)
const AdminCategoriesNewRoute = AdminCategoriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminCategoriesRoute,
} as any)
const AdminProjectsIdEditRoute = AdminProjectsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminProjectsRoute,
} as any)
const AdminProjectsIdBuyersRoute = AdminProjectsIdBuyersRouteImport.update({
  id: '/$id/buyers',
  path: '/$id/buyers',
  getParentRoute: () => AdminProjectsRoute,
} as any)
const AdminCategoriesIdEditRoute = AdminCategoriesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminCategoriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/categories': typeof AdminCategoriesRouteWithChildren
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ai/assistant': typeof AiAssistantRoute
  '/ai/career-advisor': typeof AiCareerAdvisorRoute
  '/ai/document-analyzer': typeof AiDocumentAnalyzerRoute
  '/ai/ppt-generator': typeof AiPptGeneratorRoute
  '/ai/project-advisor': typeof AiProjectAdvisorRoute
  '/ai/project-explainer': typeof AiProjectExplainerRoute
  '/ai/research-assistant': typeof AiResearchAssistantRoute
  '/ai/resume-builder': typeof AiResumeBuilderRoute
  '/ai/smart-search': typeof AiSmartSearchRoute
  '/ai/viva-generator': typeof AiVivaGeneratorRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/change-password': typeof DashboardChangePasswordRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/purchases': typeof DashboardPurchasesRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/ai/': typeof AiIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/categories/$id/edit': typeof AdminCategoriesIdEditRoute
  '/admin/projects/$id/buyers': typeof AdminProjectsIdBuyersRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/categories': typeof AdminCategoriesRouteWithChildren
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ai/assistant': typeof AiAssistantRoute
  '/ai/career-advisor': typeof AiCareerAdvisorRoute
  '/ai/document-analyzer': typeof AiDocumentAnalyzerRoute
  '/ai/ppt-generator': typeof AiPptGeneratorRoute
  '/ai/project-advisor': typeof AiProjectAdvisorRoute
  '/ai/project-explainer': typeof AiProjectExplainerRoute
  '/ai/research-assistant': typeof AiResearchAssistantRoute
  '/ai/resume-builder': typeof AiResumeBuilderRoute
  '/ai/smart-search': typeof AiSmartSearchRoute
  '/ai/viva-generator': typeof AiVivaGeneratorRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/change-password': typeof DashboardChangePasswordRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/purchases': typeof DashboardPurchasesRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin': typeof AdminIndexRoute
  '/ai': typeof AiIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/categories/$id/edit': typeof AdminCategoriesIdEditRoute
  '/admin/projects/$id/buyers': typeof AdminProjectsIdBuyersRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai': typeof AiRouteWithChildren
  '/categories': typeof CategoriesRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/categories': typeof AdminCategoriesRouteWithChildren
  '/admin/downloads': typeof AdminDownloadsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/ai/assistant': typeof AiAssistantRoute
  '/ai/career-advisor': typeof AiCareerAdvisorRoute
  '/ai/document-analyzer': typeof AiDocumentAnalyzerRoute
  '/ai/ppt-generator': typeof AiPptGeneratorRoute
  '/ai/project-advisor': typeof AiProjectAdvisorRoute
  '/ai/project-explainer': typeof AiProjectExplainerRoute
  '/ai/research-assistant': typeof AiResearchAssistantRoute
  '/ai/resume-builder': typeof AiResumeBuilderRoute
  '/ai/smart-search': typeof AiSmartSearchRoute
  '/ai/viva-generator': typeof AiVivaGeneratorRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/dashboard/change-password': typeof DashboardChangePasswordRoute
  '/dashboard/downloads': typeof DashboardDownloadsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/purchases': typeof DashboardPurchasesRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/wishlist': typeof DashboardWishlistRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/ai/': typeof AiIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin/categories/new': typeof AdminCategoriesNewRoute
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/admin/categories/$id/edit': typeof AdminCategoriesIdEditRoute
  '/admin/projects/$id/buyers': typeof AdminProjectsIdBuyersRoute
  '/admin/projects/$id/edit': typeof AdminProjectsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ai'
    | '/categories'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/admin/categories'
    | '/admin/downloads'
    | '/admin/orders'
    | '/admin/projects'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/users'
    | '/ai/assistant'
    | '/ai/career-advisor'
    | '/ai/document-analyzer'
    | '/ai/ppt-generator'
    | '/ai/project-advisor'
    | '/ai/project-explainer'
    | '/ai/research-assistant'
    | '/ai/resume-builder'
    | '/ai/smart-search'
    | '/ai/viva-generator'
    | '/categories/$slug'
    | '/checkout/success'
    | '/dashboard/change-password'
    | '/dashboard/downloads'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/purchases'
    | '/dashboard/transactions'
    | '/dashboard/wishlist'
    | '/projects/$id'
    | '/admin/'
    | '/ai/'
    | '/dashboard/'
    | '/admin/categories/new'
    | '/admin/projects/new'
    | '/admin/categories/$id/edit'
    | '/admin/projects/$id/buyers'
    | '/admin/projects/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/categories'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/admin/categories'
    | '/admin/downloads'
    | '/admin/orders'
    | '/admin/projects'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/users'
    | '/ai/assistant'
    | '/ai/career-advisor'
    | '/ai/document-analyzer'
    | '/ai/ppt-generator'
    | '/ai/project-advisor'
    | '/ai/project-explainer'
    | '/ai/research-assistant'
    | '/ai/resume-builder'
    | '/ai/smart-search'
    | '/ai/viva-generator'
    | '/categories/$slug'
    | '/checkout/success'
    | '/dashboard/change-password'
    | '/dashboard/downloads'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/purchases'
    | '/dashboard/transactions'
    | '/dashboard/wishlist'
    | '/projects/$id'
    | '/admin'
    | '/ai'
    | '/dashboard'
    | '/admin/categories/new'
    | '/admin/projects/new'
    | '/admin/categories/$id/edit'
    | '/admin/projects/$id/buyers'
    | '/admin/projects/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ai'
    | '/categories'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/admin/categories'
    | '/admin/downloads'
    | '/admin/orders'
    | '/admin/projects'
    | '/admin/revenue'
    | '/admin/settings'
    | '/admin/users'
    | '/ai/assistant'
    | '/ai/career-advisor'
    | '/ai/document-analyzer'
    | '/ai/ppt-generator'
    | '/ai/project-advisor'
    | '/ai/project-explainer'
    | '/ai/research-assistant'
    | '/ai/resume-builder'
    | '/ai/smart-search'
    | '/ai/viva-generator'
    | '/categories/$slug'
    | '/checkout/success'
    | '/dashboard/change-password'
    | '/dashboard/downloads'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/purchases'
    | '/dashboard/transactions'
    | '/dashboard/wishlist'
    | '/projects/$id'
    | '/admin/'
    | '/ai/'
    | '/dashboard/'
    | '/admin/categories/new'
    | '/admin/projects/new'
    | '/admin/categories/$id/edit'
    | '/admin/projects/$id/buyers'
    | '/admin/projects/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiRoute: typeof AiRouteWithChildren
  CategoriesRoute: typeof CategoriesRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/ai/': {
      id: '/ai/'
      path: '/'
      fullPath: '/ai/'
      preLoaderRoute: typeof AiIndexRouteImport
      parentRoute: typeof AiRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wishlist': {
      id: '/dashboard/wishlist'
      path: '/wishlist'
      fullPath: '/dashboard/wishlist'
      preLoaderRoute: typeof DashboardWishlistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/purchases': {
      id: '/dashboard/purchases'
      path: '/purchases'
      fullPath: '/dashboard/purchases'
      preLoaderRoute: typeof DashboardPurchasesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/downloads': {
      id: '/dashboard/downloads'
      path: '/downloads'
      fullPath: '/dashboard/downloads'
      preLoaderRoute: typeof DashboardDownloadsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/change-password': {
      id: '/dashboard/change-password'
      path: '/change-password'
      fullPath: '/dashboard/change-password'
      preLoaderRoute: typeof DashboardChangePasswordRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/ai/viva-generator': {
      id: '/ai/viva-generator'
      path: '/viva-generator'
      fullPath: '/ai/viva-generator'
      preLoaderRoute: typeof AiVivaGeneratorRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/smart-search': {
      id: '/ai/smart-search'
      path: '/smart-search'
      fullPath: '/ai/smart-search'
      preLoaderRoute: typeof AiSmartSearchRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/resume-builder': {
      id: '/ai/resume-builder'
      path: '/resume-builder'
      fullPath: '/ai/resume-builder'
      preLoaderRoute: typeof AiResumeBuilderRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/research-assistant': {
      id: '/ai/research-assistant'
      path: '/research-assistant'
      fullPath: '/ai/research-assistant'
      preLoaderRoute: typeof AiResearchAssistantRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/project-explainer': {
      id: '/ai/project-explainer'
      path: '/project-explainer'
      fullPath: '/ai/project-explainer'
      preLoaderRoute: typeof AiProjectExplainerRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/project-advisor': {
      id: '/ai/project-advisor'
      path: '/project-advisor'
      fullPath: '/ai/project-advisor'
      preLoaderRoute: typeof AiProjectAdvisorRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/ppt-generator': {
      id: '/ai/ppt-generator'
      path: '/ppt-generator'
      fullPath: '/ai/ppt-generator'
      preLoaderRoute: typeof AiPptGeneratorRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/document-analyzer': {
      id: '/ai/document-analyzer'
      path: '/document-analyzer'
      fullPath: '/ai/document-analyzer'
      preLoaderRoute: typeof AiDocumentAnalyzerRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/career-advisor': {
      id: '/ai/career-advisor'
      path: '/career-advisor'
      fullPath: '/ai/career-advisor'
      preLoaderRoute: typeof AiCareerAdvisorRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/assistant': {
      id: '/ai/assistant'
      path: '/assistant'
      fullPath: '/ai/assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof AiRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/downloads': {
      id: '/admin/downloads'
      path: '/downloads'
      fullPath: '/admin/downloads'
      preLoaderRoute: typeof AdminDownloadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/new': {
      id: '/admin/projects/new'
      path: '/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/categories/new': {
      id: '/admin/categories/new'
      path: '/new'
      fullPath: '/admin/categories/new'
      preLoaderRoute: typeof AdminCategoriesNewRouteImport
      parentRoute: typeof AdminCategoriesRoute
    }
    '/admin/projects/$id/edit': {
      id: '/admin/projects/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/projects/$id/edit'
      preLoaderRoute: typeof AdminProjectsIdEditRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/projects/$id/buyers': {
      id: '/admin/projects/$id/buyers'
      path: '/$id/buyers'
      fullPath: '/admin/projects/$id/buyers'
      preLoaderRoute: typeof AdminProjectsIdBuyersRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/categories/$id/edit': {
      id: '/admin/categories/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/categories/$id/edit'
      preLoaderRoute: typeof AdminCategoriesIdEditRouteImport
      parentRoute: typeof AdminCategoriesRoute
    }
  }
}

interface AdminCategoriesRouteChildren {
  AdminCategoriesNewRoute: typeof AdminCategoriesNewRoute
  AdminCategoriesIdEditRoute: typeof AdminCategoriesIdEditRoute
}

const AdminCategoriesRouteChildren: AdminCategoriesRouteChildren = {
  AdminCategoriesNewRoute: AdminCategoriesNewRoute,
  AdminCategoriesIdEditRoute: AdminCategoriesIdEditRoute,
}

const AdminCategoriesRouteWithChildren = AdminCategoriesRoute._addFileChildren(
  AdminCategoriesRouteChildren,
)

interface AdminProjectsRouteChildren {
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
  AdminProjectsIdBuyersRoute: typeof AdminProjectsIdBuyersRoute
  AdminProjectsIdEditRoute: typeof AdminProjectsIdEditRoute
}

const AdminProjectsRouteChildren: AdminProjectsRouteChildren = {
  AdminProjectsNewRoute: AdminProjectsNewRoute,
  AdminProjectsIdBuyersRoute: AdminProjectsIdBuyersRoute,
  AdminProjectsIdEditRoute: AdminProjectsIdEditRoute,
}

const AdminProjectsRouteWithChildren = AdminProjectsRoute._addFileChildren(
  AdminProjectsRouteChildren,
)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRouteWithChildren
  AdminDownloadsRoute: typeof AdminDownloadsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProjectsRoute: typeof AdminProjectsRouteWithChildren
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRouteWithChildren,
  AdminDownloadsRoute: AdminDownloadsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProjectsRoute: AdminProjectsRouteWithChildren,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AiRouteChildren {
  AiAssistantRoute: typeof AiAssistantRoute
  AiCareerAdvisorRoute: typeof AiCareerAdvisorRoute
  AiDocumentAnalyzerRoute: typeof AiDocumentAnalyzerRoute
  AiPptGeneratorRoute: typeof AiPptGeneratorRoute
  AiProjectAdvisorRoute: typeof AiProjectAdvisorRoute
  AiProjectExplainerRoute: typeof AiProjectExplainerRoute
  AiResearchAssistantRoute: typeof AiResearchAssistantRoute
  AiResumeBuilderRoute: typeof AiResumeBuilderRoute
  AiSmartSearchRoute: typeof AiSmartSearchRoute
  AiVivaGeneratorRoute: typeof AiVivaGeneratorRoute
  AiIndexRoute: typeof AiIndexRoute
}

const AiRouteChildren: AiRouteChildren = {
  AiAssistantRoute: AiAssistantRoute,
  AiCareerAdvisorRoute: AiCareerAdvisorRoute,
  AiDocumentAnalyzerRoute: AiDocumentAnalyzerRoute,
  AiPptGeneratorRoute: AiPptGeneratorRoute,
  AiProjectAdvisorRoute: AiProjectAdvisorRoute,
  AiProjectExplainerRoute: AiProjectExplainerRoute,
  AiResearchAssistantRoute: AiResearchAssistantRoute,
  AiResumeBuilderRoute: AiResumeBuilderRoute,
  AiSmartSearchRoute: AiSmartSearchRoute,
  AiVivaGeneratorRoute: AiVivaGeneratorRoute,
  AiIndexRoute: AiIndexRoute,
}

const AiRouteWithChildren = AiRoute._addFileChildren(AiRouteChildren)

interface CategoriesRouteChildren {
  CategoriesSlugRoute: typeof CategoriesSlugRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesSlugRoute: CategoriesSlugRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface DashboardRouteChildren {
  DashboardChangePasswordRoute: typeof DashboardChangePasswordRoute
  DashboardDownloadsRoute: typeof DashboardDownloadsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardPurchasesRoute: typeof DashboardPurchasesRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardWishlistRoute: typeof DashboardWishlistRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChangePasswordRoute: DashboardChangePasswordRoute,
  DashboardDownloadsRoute: DashboardDownloadsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardPurchasesRoute: DashboardPurchasesRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardWishlistRoute: DashboardWishlistRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AiRoute: AiRouteWithChildren,
  CategoriesRoute: CategoriesRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ProjectsIdRoute: ProjectsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
